# yaml-language-server: $schema=https://raw.githubusercontent.com/Azure/azure-dev/main/schemas/v1.0/azure.yaml.json

name: workshoplab
metadata:
    template: workshoplab-foundry-hosted-agent
services:
    hosted-agent-readiness-coach:
        project: ./src/WorkshopLab.AgentHost
        host: azure.ai.agent
        language: docker
        docker:
            path: ./Dockerfile
            context: ../
            remoteBuild: true
        config:
            container:
                resources:
                    cpu: "0.5"
                    memory: 1Gi
            deployments:
                - model:
                    format: OpenAI
                    name: gpt-5.4-mini
                    version: "2026-03-17"
                  name: gpt-5.4-mini
                  sku:
                    capacity: 10
                    name: GlobalStandard
            startupCommand: dotnet run
infra:
    provider: bicep
pipeline:
    provider: github
    variables: []
    secrets: []
